---
# Localhost inventory for configuring the local machine as NFS client
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      
      # Kerberos configuration
      krb5_realm: "CUBE.K8S"
      krb5_kdc: "kdc.cube.k8s"
      krb5_admin_server: "kdc.cube.k8s"
      
      # NFS client configuration
      nfs_domain: "cube.k8s"
      nfs_enable_kerberos: true
      nfs_enable_v4: true
      nfs_enable_v3: true
      nfs_enable_v2: false
